export const lashesTemplate = [
  {
    label: 'Cel wizyty',
    value: [],
    identifier: 'purpose',
    optionalValues: ['Nowa aplikacja', 'Uzupełnienie rzęs', 'Zdejmowanie rzęs'],
    description: '',
  },
  {
    label: 'Marka rzęs',
    value: [],
    identifier: 'lashesBrand',
    optionalValues: ['Noble', 'Itlm', 'Lashes design'],
    description: '',
  },
  {
    label: 'Klej',
    value: [],
    identifier: 'glue',
    optionalValues: [],
    description: '',
  },
  {
    label: 'Remover',
    value: [],
    identifier: 'remover',
    optionalValues: [],
    description: '',
  },
  {
    label: 'Metoda',
    value: [],
    identifier: 'method',
    optionalValues: ['2d', '2/3d', '3d', '4/6d', '5/8d', 'MV'],
    description: '',
  },
  {
    label: 'Skręt',
    value: [],
    identifier: 'curve',
    optionalValues: ['L', 'M', 'B', 'C', 'C+', 'D', 'D+'],
    description: '',
  },
  {
    label: 'Grubość',
    value: [],
    identifier: 'width',
    optionalValues: [0.03, 0.05, 0.07, 0.1],
    description: '',
  },
  {
    label: 'Długość',
    value: [],
    identifier: 'length',
    optionalValues: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    description: '',
  },
  {
    label: 'Struktura na oku',
    value: [],
    identifier: 'modeling',
    optionalValues: [],
    description: '',
  },
  {
    label: 'Modelowanie',
    value: [],
    identifier: 'lashesModelingType',
    optionalValues: ['Lalka', 'Wiewiórka', 'Kocie oko'],
    description: '',
  },
];
